audio:
  chunk_size: 261120
  dim_f: 4096
  dim_t: 256
  hop_length: 1024
  min_mean_abs: 0.001
  n_fft: 8192
  num_channels: 2
  sample_rate: 44100

model:
  act: gelu
  bottleneck_factor: 5
  growth: 224
  norm: InstanceNorm
  num_blocks_per_scale: 4
  num_channels: 48
  num_scales: 4
  num_subbands: 4
  scale:
  - 2
  - 2

training:
  batch_size: 4
  coarse_loss_clip: true
  ema_momentum: 0.9843434567317182
  grad_clip: 0
  gradient_accumulation_steps: 1
  instruments:
  - vocals
  - bass
  - drums
  - other
  lr: 9.895019867581646e-05
  num_epochs: 1000
  num_steps: 1000
  optimizer: adamw
  other_fix: false
  patience: 8
  q: 0.95
  reduce_factor: 0.3067220909070577
  target_instrument: null
  use_amp: true

inference:
  batch_size: 1
  dim_t: 128
  num_overlap: 8