audio:
  chunk_size: 485100 # 44100 * 11
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.000

model:
  sources:
    - drums
    - bass
    - other
    - vocals
  audio_channels: 2
  dims:
    - 4
    - 32
    - 64
    - 128
  nfft: 4096
  hop_size: 1024
  win_size: 2048
  normalized: True
  band_SR:
    - 0.19013175747332464
    - 0.3629376118427377
    - 0.5397970761846854
  band_stride:
    - 2
    - 2
    - 8
  band_kernel:
    - 3
    - 3
    - 11
  conv_depths:
    - 3
    - 2
    - 1
  compress: 2
  conv_kernel: 4
  num_dplayer: 7
  expand: 4

training:
  batch_size: 9
  gradient_accumulation_steps: 10
  grad_clip: 0
  instruments:
    - drums
    - bass
    - other
    - vocals
  lr: 0.0004595695931905895
  patience: 2
  reduce_factor: 0.8959688194600346
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.9707069996265402
  optimizer: adamw
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true

augmentations:
  enable: true # enable or disable all augmentations (to fast disable if needed)
  loudness: true # randomly change loudness of each stem on the range (loudness_min; loudness_max)
  loudness_min: 0.96395947987773
  loudness_max: 1.7864084910560143
  mixup: true # mix several stems of same type with some probability (only works for dataset types: 1, 2, 3)
  mixup_probs:
    !!python/tuple # 2 additional stems of the same type (1st with prob 0.2, 2nd with prob 0.02)
    - 0.2
    - 0.02
  mixup_loudness_min: 0.1792918702537118
  mixup_loudness_max: 0.02238830261506526

inference:
  batch_size: 8
  dim_t: 192
  num_overlap: 4
  normalize: true
