audio:
  chunk_size: 485100
  min_mean_abs: 0.0
  num_channels: 2
  sample_rate: 44100
augmentations:
  enable: true
  loudness: true
  loudness_max: 1.7864084910560143
  loudness_min: 0.96395947987773
  mixup: true
  mixup_loudness_max: 1.5
  mixup_loudness_min: 0.5
  mixup_probs: !!python/tuple
  - 0.1792918702537118
  - 0.02238830261506526
inference:
  batch_size: 8
  dim_t: 192
  normalize: true
  num_overlap: 4
model:
  audio_channels: 2
  band_SR:
  - 0.19013175747332464
  - 0.3629376118427377
  - 0.5397970761846854
  band_kernel:
  - 3
  - 3
  - 11
  band_stride:
  - 2
  - 2
  - 8
  # chunk_size: 573300
  compress: 2
  conv_depths:
  - 3
  - 2
  - 1
  conv_kernel: 4
  dims:
  - 4
  - 32
  - 64
  - 128
  expand: 4
  hop_size: 1024
  nfft: 4096
  normalized: true
  num_dplayer: 7
  sources:
  - drums
  - bass
  - other
  - vocals
  win_size: 2048
training:
  batch_size: 9
  coarse_loss_clip: true
  ema_momentum: 0.9707069996265402
  grad_clip: 0
  gradient_accumulation_steps: 10
  instruments:
  - drums
  - bass
  - other
  - vocals
  lr: 0.0004595695931905895
  num_epochs: 50
  num_steps: 1000
  optimizer: adamw
  other_fix: false
  patience: 2
  q: 0.95
  reduce_factor: 0.8959688194600346
  target_instrument: null
  use_amp: true
